version: '3.4'

services: 
  cicdimplementation:
    image: ci-cd-implementation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
